version: "3.8"

services:
  nginx:
    build: ./nginx/
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "9090:80"
    links:
      - php-fpm

  php-fpm:
    build: ./
    volumes:
      - ./src:/usr/share/nginx/html
    expose:
      - "9000"
