version: "3.8"

services:
  nginx:
    build: ./nginx/
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    build: ./
    volumes:
      - ./src:/usr/share/nginx/html
    expose:
      - "9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

